DROP DATABASE IF EXISTS fun_corpDB;
CREATE database fun_corpDB;
​
USE fun_corpDB;

-- CREATE TABLE DEPARTMENT
CREATE TABLE DEPARTMENT(
   ID INTEGER(11) AUTO_INCREMENT NOT NULL,
   DEPTNAME VARCHAR(100),
   PRIMARY KEY (ID)
);
​
CREATE TABLE ROLE_ (
  ID INTEGER(11) AUTO_INCREMENT NOT NULL,
  TITLE VARCHAR(30), 
  SALARY DECIMAL(10,4) NULL, 
  DEPTID INTEGER(11) NULL, 
  FOREIGN KEY (DEPTID) REFERENCES DEPARTMENT(ID), 
  PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE (
  ID INTEGER(11) AUTO_INCREMENT NOT NULL,
  FIRSTNAME VARCHAR(30),
  LASTNAME VARCHAR(30),
  ROLEID INTEGER(11) NULL, 
  MANAGERID INTEGER(11) NULL, 
  FOREIGN KEY (ROLEID) REFERENCES ROLE_(ID),
  FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(ID),
  PRIMARY KEY (ID)
);
​

